const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const {createUpdates,installedWindowsApp}=require('../src/app-updates');
function fixture(options={}){const driver=new EventEmitter();let downloads=0,installed=false,saved=false;driver.checkForUpdates=async()=>{driver.emit('checking-for-update');driver.emit('update-available',{version:'0.2.1'});};driver.downloadUpdate=async()=>{downloads++;driver.emit('download-progress',{percent:50});driver.emit('update-downloaded',{version:'0.2.1'});};driver.quitAndInstall=()=>{installed=true;};const updates=createUpdates({app:{isPackaged:true,getVersion:()=> '0.2.0'},driver,emit:()=>{},busy:()=>false,beforeInstall:async()=>{saved=true;},...options});return {updates,driver,get downloads(){return downloads;},get installed(){return installed;},get saved(){return saved;}};}
test('update checks do not download or restart without explicit actions',async()=>{const f=fixture();assert.equal(f.driver.autoDownload,false);assert.equal(f.driver.autoInstallOnAppQuit,false);await f.updates.action('check');assert.equal(f.updates.snapshot().status,'available');assert.equal(f.downloads,0);await f.updates.action('download');assert.equal(f.updates.snapshot().status,'ready');assert.equal(f.installed,false);await f.updates.action('install');assert.equal(f.installed,true);assert.equal(f.saved,true);});
test('ready updates cannot interrupt an active task or voice conversation',async()=>{const f=fixture({busy:()=>true});await f.updates.action('check');await f.updates.action('download');await assert.rejects(f.updates.action('install'),/Finish or stop/);assert.equal(f.installed,false);});
test('development copies never contact update servers',async()=>{const f=fixture({enabled:false});assert.equal(f.updates.snapshot().status,'development');await assert.rejects(f.updates.action('check'),/installed app/);assert.equal(f.downloads,0);});
test('failed downloads leave the current app running and can be retried',async()=>{const f=fixture();await f.updates.action('check');f.driver.downloadUpdate=async()=>{throw Error('network with sensitive details');};await f.updates.action('download');assert.equal(f.updates.snapshot().status,'error');assert.ok(!f.updates.snapshot().error.includes('sensitive'));assert.equal(f.installed,false);await f.updates.action('check');assert.equal(f.updates.snapshot().status,'available');});
test('concurrent checks share one request and a ready download stays ready',async()=>{const f=fixture();let finish,count=0;f.driver.checkForUpdates=()=>{count++;return new Promise(resolve=>{finish=resolve;});};const one=f.updates.action('check'),two=f.updates.action('check');assert.equal(count,1);finish();await Promise.all([one,two]);f.driver.emit('update-downloaded',{version:'0.2.1'});await f.updates.action('check');assert.equal(count,1);assert.equal(f.updates.snapshot().status,'ready');});
test('packaged unpacked directories do not enable installer updates',()=>{const app={isPackaged:true,getPath:()=>require('node:path').resolve('fixture','Heartflow Aurora.exe')};assert.equal(installedWindowsApp(app,()=>false),false);assert.equal(installedWindowsApp(app,file=>file.endsWith('Uninstall Heartflow Aurora.exe')),true);assert.equal(installedWindowsApp({...app,isPackaged:false},()=>true),false);});
