const test = require('node:test'), assert = require('node:assert/strict');
const {chat,listModels,openaiInput,anthropicMessages,routerMessages} = require('../src/provider-adapters');
const settings = require('../src/provider-settings');
const ollama = require('../src/provider');
const tool = {type:'function',function:{name:'read_file',description:'Read text',parameters:{type:'object',properties:{path:{type:'string'}},required:['path']}}};
function stream(items,inspect){return async(url,options)=>{inspect?.(url,options);const text=items.map(i=>`data: ${typeof i==='string'?i:JSON.stringify(i)}\r\n\r\n`).join('');return new Response(new ReadableStream({start(c){for(let n=0;n<text.length;n+=13)c.enqueue(new TextEncoder().encode(text.slice(n,n+13)));c.close();}}));};}
test('legacy Ollama keys migrate without being decrypted or exposed',()=>{const data={model:'old-model',encryptedKey:'encrypted-blob'};settings.normalize(data);assert.equal(data.provider,'ollama-cloud');assert.equal(data.connections['ollama-cloud'].encryptedKey,'encrypted-blob');assert.equal(settings.snapshot(data)['ollama-cloud'].hasKey,true);assert.ok(!JSON.stringify(settings.snapshot(data)).includes('encrypted-blob'));data.connections.openai={model:'my-model',encryptedKey:'another-key'};data.provider='openai';settings.normalize(data);assert.equal(data.model,'my-model');assert.equal(data.connections['ollama-cloud'].model,'old-model');});
test('local connection is restricted to loopback without credentials or URL suffixes',()=>{assert.equal(settings.localUrl(),'http://127.0.0.1:11434');assert.equal(settings.localUrl('http://localhost:11434/'),'http://localhost:11434');for(const value of ['https://example.com','http://localhost:11434/api','file:///tmp','http://user:secret@localhost:11434','http://127.0.0.1:11434/?key=secret'])assert.throws(()=>settings.localUrl(value));});
test('local Ollama sends no key and strips foreign response metadata',async()=>{const result=await ollama.chat({provider:'ollama-local',model:'local',messages:[{role:'user',content:'hello',_output:'private-provider-state'}],tools:[],fetcher:async(url,opts)=>{assert.equal(url,'http://127.0.0.1:11434/api/chat');assert.equal(opts.headers.Authorization,undefined);assert.equal(JSON.parse(opts.body).messages[0]._output,undefined);return new Response('{"message":{"content":"Hello"},"done":true}\n');}});assert.equal(result.content,'Hello');});
test('OpenAI streams text and keeps raw reasoning and call IDs for the next turn',async()=>{let payload;const output=[{type:'reasoning',id:'r_1',summary:[]},{type:'function_call',id:'fc_1',call_id:'call_1',name:'read_file',arguments:'{"path":"a.txt"}'}];const text=[];const result=await chat({provider:'openai',key:'test-key',model:'test',messages:[{role:'system',content:'Rules'},{role:'user',content:'Read a'}],tools:[tool],onText:t=>text.push(t),fetcher:stream([{type:'response.output_text.delta',delta:'Checking'},{type:'response.completed',response:{output}}],(url,opts)=>{assert.equal(url,'https://api.openai.com/v1/responses');payload=JSON.parse(opts.body);})});assert.equal(payload.store,false);assert.equal(payload.instructions,'Rules');assert.equal(payload.tools[0].name,'read_file');assert.equal(result.tool_calls[0].id,'call_1');assert.deepEqual(text,['Checking']);const follow=openaiInput([{role:'user',content:'Read a'},result,{role:'tool',tool_name:'read_file',tool_call_id:'call_1',content:'file contents'}]);assert.deepEqual(follow.slice(1,3),output);assert.equal(follow.at(-1).call_id,'call_1');});
test('Claude receives native tools and reconstructs partial argument JSON',async()=>{let payload;const result=await chat({provider:'anthropic',key:'test',model:'test',messages:[{role:'system',content:'Rules'},{role:'user',content:'Read a'}],tools:[tool],fetcher:stream([{type:'content_block_start',index:0,content_block:{type:'tool_use',id:'toolu_1',name:'read_file',input:{}}},{type:'content_block_delta',index:0,delta:{type:'input_json_delta',partial_json:'{"path":'}},{type:'content_block_delta',index:0,delta:{type:'input_json_delta',partial_json:'"a.txt"}'}},{type:'message_delta',delta:{stop_reason:'tool_use'}},{type:'message_stop'}],(url,opts)=>{assert.equal(opts.headers['x-api-key'],'test');assert.equal(opts.headers.Authorization,'');payload=JSON.parse(opts.body);})});assert.equal(payload.tools[0].input_schema.type,'object');assert.equal(result.tool_calls[0].function.arguments.path,'a.txt');const follow=anthropicMessages([result,{role:'tool',tool_name:'read_file',tool_call_id:'toolu_1',content:'contents'}]);assert.equal(follow[0].content[0].id,follow[1].content[0].tool_use_id);});
test('OpenRouter reconstructs split calls and serializes follow-up arguments',async()=>{const result=await chat({provider:'openrouter',key:'test',model:'test',messages:[],tools:[tool],fetcher:stream([{choices:[{delta:{tool_calls:[{index:0,id:'call_router',function:{name:'read_file',arguments:'{"path":'}}]}}]},{choices:[{delta:{tool_calls:[{index:0,function:{arguments:'"a.txt"}'}}]},finish_reason:'tool_calls'}]},'[DONE]'])});assert.equal(result.tool_calls[0].function.arguments.path,'a.txt');const follow=routerMessages([result,{role:'tool',tool_name:'read_file',content:'contents'}]);assert.equal(follow[1].tool_call_id,'call_router');assert.equal(follow[0].tool_calls[0].function.arguments,'{"path":"a.txt"}');});
test('legacy parallel calls retain matching IDs across all cloud formats',()=>{const history=[{role:'assistant',content:'',tool_calls:[{function:{name:'read_file',arguments:{path:'a'}}},{function:{name:'read_file',arguments:{path:'b'}}}]},{role:'tool',tool_name:'read_file',content:'a'},{role:'tool',tool_name:'read_file',content:'b'}];const input=openaiInput(history);assert.equal(input[0].call_id,input[2].call_id);assert.equal(input[1].call_id,input[3].call_id);const anthropic=anthropicMessages(history);assert.equal(anthropic[1].content.length,2);assert.equal(anthropic[0].content[1].id,anthropic[1].content[1].tool_use_id);});
test('incomplete and truncated streams do not execute partial tool calls',async()=>{for(const provider of ['openai','anthropic','openrouter'])await assert.rejects(chat({provider,key:'test',model:'test',messages:[],fetcher:stream([])}),/ended early/);await assert.rejects(chat({provider:'openai',key:'test',model:'test',messages:[],fetcher:stream([{type:'response.incomplete'}])}),/did not finish/);await assert.rejects(chat({provider:'anthropic',key:'test',model:'test',messages:[],fetcher:stream([{type:'message_delta',delta:{stop_reason:'max_tokens'}}])}),/response limit/);});
test('provider HTTP errors redact API keys and preserve abort signals',async()=>{const signal=new AbortController();signal.abort();await assert.rejects(chat({provider:'openai',key:'secret',model:'test',messages:[],signal:signal.signal,fetcher:async(_url,options)=>{assert.ok(options.signal.aborted);return new Response('secret failure',{status:500});}}),error=>error.message.includes('[redacted]')&&!error.message.includes('secret'));});
test('OpenRouter discovery lists only models advertising tool support',async()=>{const models=await listModels({provider:'openrouter',key:'test',fetcher:async()=>new Response(JSON.stringify({data:[{id:'tools',supported_parameters:['tools']},{id:'plain',supported_parameters:[]}]}))});assert.deepEqual(models,['tools']);});
test('switching models keeps tool history but drops incompatible opaque reasoning',()=>{const history=[{role:'assistant',content:'Working',_provider:'openai',_model:'previous',_output:[{type:'reasoning',id:'opaque-old'}],tool_calls:[{id:'call_1',function:{name:'read_file',arguments:{path:'a'}}}]},{role:'tool',tool_call_id:'call_1',content:'contents'}];const next=openaiInput(history,'new-model');assert.ok(!JSON.stringify(next).includes('opaque-old'));assert.equal(next.at(-1).call_id,'call_1');const router=routerMessages([{role:'assistant',content:'Working',_provider:'openrouter',_model:'previous',reasoning_details:[{data:'opaque-old'}]}],'new-model');assert.equal(router[0].reasoning_details,undefined);});
test('stopping halfway through parallel calls keeps the next request valid without claiming success',()=>{const history=[{role:'assistant',content:'',tool_calls:[{id:'first',function:{name:'read_file',arguments:{path:'a'}}},{id:'second',function:{name:'write_file',arguments:{path:'b',content:'text'}}}]},{role:'tool',tool_call_id:'first',tool_name:'read_file',content:'read result'},{role:'user',content:'Try something else'}];const input=openaiInput(history);assert.equal(input[3].call_id,'second');assert.match(input[3].output,/interrupted/);assert.equal(input[4].content,'Try something else');const anthropic=anthropicMessages(history);assert.equal(anthropic[1].content[1].tool_use_id,'second');assert.match(anthropic[1].content[1].content,/No success/);assert.equal(routerMessages([{role:'tool',tool_name:'unknown',content:'orphan'}]).length,0);});
