// Real minimized Electron UI and PCM playback, mock speech/model/browser; no paid calls or input.
const {app,BrowserWindow}=require('electron'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const root=process.env.AURORA_SMOKE_SOURCE||path.resolve('src'),output=path.resolve('test-output',`emotion-smoke-${Date.now()}`);app.setPath('userData',path.join(output,'profile'));
let recognized,step=0;const bodies=[],events=[];
require(path.join(root,'voice-recognizer')).createRecognizer=({onEvent})=>{recognized=onEvent;return {start:async()=>{},mode:async()=>{},stop(){}};};
require(path.join(root,'computer-control')).createComputerControl=()=>({open:async()=>({observation:{process:'opera',windowId:'fixture',title:'Requested song · YouTube',controls:[{id:'v2:1',name:'Pause (k)',kind:'Button'}]}}),cancel(){},action:async()=>({})});
const speech=require(path.join(root,'voice-provider')),original=speech.synthesize;speech.synthesize=options=>original({...options,fetchImpl:async(_,opts)=>{bodies.push(JSON.parse(opts.body));return new Response(new ReadableStream({start(controller){controller.enqueue(new Uint8Array(4800));setTimeout(()=>{controller.enqueue(new Uint8Array(4800));controller.close();},150);}}),{headers:{'content-type':'audio/pcm'}});}});
const tool=(name,args)=>({role:'assistant',content:'',tool_calls:[{function:{name,arguments:args}}]});require(path.join(root,'provider')).chat=async()=>{switch(step++){case 0:return tool('open_application',{application:'opera',url:'https://www.youtube.com/watch?v=fixture'});case 1:return tool('voice_reply',{spoken:'The song is playing.',written:'Playback verified on the requested video.',emotion:'happy',completion:'music_playback'});case 2:return tool('voice_reply',{spoken:'[happy] Ah, found it.',written:'[happy] Here is your answer.',emotion:'happy'});default:throw Error('Unexpected model call');}};
require(path.join(root,'main'));const pause=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn){for(let i=0;i<200;i++){if(await fn())return;await pause(40);}throw Error('Emotion check timed out at '+step);}
app.whenReady().then(async()=>{try{await fs.mkdir(output,{recursive:true});let win,notch;await until(()=>{win=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('index.html'));notch=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('notch.html'));return win&&notch&&!win.webContents.isLoading()&&!notch.webContents.isLoading();});const js=s=>win.webContents.executeJavaScript(s),load=async()=>(await js('window.aurora.load()')).value;
 const send=win.webContents.send.bind(win.webContents);win.webContents.send=(channel,value)=>{if(channel==='event')events.push(value);return send(channel,value);};
 await js('window.aurora.saveSettings({key:"fixture",model:"fixture"})');await js('window.aurora.voiceSettings({provider:"fish",key:"fixture",voiceId:"fixture",recognizerId:"",fishModel:"s2.1-pro"})');await js('window.aurora.voiceToggle(true)');win.showInactive();win.minimize();
 recognized({type:'wake'});await until(async()=>(await load()).voice.status==='listening');assert.ok(bodies[0].text.startsWith('[soft tone]'));
 recognized({type:'text',text:'Play the requested song on YouTube'});await until(async()=>(await load()).voice.status==='wake'&&step===2);assert.equal(bodies.at(-1).text,'[calm] Enjoy the music.');assert.ok((await load()).voice.enabled);await until(()=>!notch.isVisible());assert.ok(win.isMinimized());
 recognized({type:'wake'});await until(async()=>(await load()).voice.status==='listening');recognized({type:'text',text:'Tell me something cheerful'});await until(async()=>(await load()).voice.status==='listening'&&step===3);assert.equal(bodies.at(-1).text,'[happy] Ah, found it.');assert.ok(events.some(e=>e.type==='voice-expression'&&e.active&&e.emotion==='happy'&&e.pose==='celebrating'));assert.ok(events.some(e=>e.type==='voice-expression'&&!e.active));
 assert.ok(events.filter(e=>e.type==='voice-state').every(e=>!e.voice.detail.includes('[happy]')&&!e.voice.detail.includes('[calm]')));assert.ok((await load()).messages.filter(m=>m.role==='assistant'&&m.content).every(m=>!m.content.includes('[happy]')));assert.ok(notch.isVisible());await fs.writeFile(path.join(output,'notch.png'),(await notch.webContents.capturePage()).toPNG());
 await js('window.aurora.voiceToggle(false)');await fs.writeFile(path.join(output,'result.json'),JSON.stringify({passed:true,fishCues:true,hiddenTags:true,matchingPose:true,musicSignoff:true,wakeRemainsEnabled:true,notchHides:true}));console.log('Emotion smoke passed: '+output);app.exit(0);
 }catch(error){await fs.mkdir(output,{recursive:true});await fs.writeFile(path.join(output,'result.json'),JSON.stringify({passed:false,error:error.stack,step}));console.error(error);app.exit(1);}});
