// Isolated project/session UI, migration and persistence. No real API calls or microphone.
const {app,BrowserWindow,dialog}=require('electron'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const output=path.resolve('test-output',`library-smoke-${Date.now()}`),profile=path.join(output,'profile'),root=process.env.AURORA_SMOKE_SOURCE||path.resolve('src');app.setPath('userData',profile);
const pause=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn){for(let i=0;i<150;i++){if(await fn())return;await pause(60);}throw Error('Library check timed out.');}
let resolveTask;
require(path.join(root,'provider')).chat=async({messages,signal})=>{assert.match(messages[0].content,/Current mode: Aurora Code/);return new Promise((resolve,reject)=>{resolveTask=()=>resolve({role:'assistant',content:'The cactus website is ready.'});signal.addEventListener('abort',()=>reject(Error('Stopped')),{once:true});});};
{const sync=require('node:fs');sync.mkdirSync(profile,{recursive:true});sync.writeFileSync(path.join(profile,'aurora.json'),JSON.stringify({model:'',workspace:'',encryptedKey:'',currentId:'legacy',chats:[{id:'legacy',title:'Earlier conversation',created:1,messages:[{role:'user',content:'My cactus needs sunlight.'},{role:'assistant',content:'Choose a bright spot.'}]}]}));}require(path.join(root,'main'));
app.whenReady().then(async()=>{try{
 let win;await until(()=>{win=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('index.html'));return win&&!win.webContents.isLoading();});const js=s=>win.webContents.executeJavaScript(s),load=async()=>{const r=await js('window.aurora.load()');assert.ok(r.ok);return r.value;};
 await until(()=>js('!!document.querySelector(".chat-link")'));assert.equal((await load()).currentId,'legacy');
 await js('document.getElementById("project-add").click();document.getElementById("project-name").value="Cactus website";document.getElementById("project-form").requestSubmit()');await until(async()=>(await load()).projects.length===1);await until(()=>js('!document.getElementById("project-dialog").open'));
 const project=(await load()).activeProjectId;const folder=path.join(output,'workspace');await fs.mkdir(folder);dialog.showOpenDialog=async()=>({canceled:false,filePaths:[folder]});await js('document.getElementById("workspace").click()');await until(async()=>(await load()).workspace===folder);
 await js('document.getElementById("mode-code").click()');await until(async()=>(await load()).mode==='code');await until(()=>js('document.body.dataset.mode==="code"'));
 win.showInactive();await pause(250);await fs.writeFile(path.join(output,'code.png'),(await win.webContents.capturePage()).toPNG());const codeId=(await load()).currentId;
 await js('(async()=>render((await window.aurora.saveSettings({key:"fixture-key",model:"fixture"})).value))()');await js('document.getElementById("prompt").value="Build a cactus website";document.getElementById("composer").requestSubmit()');await until(()=>!!resolveTask);assert.equal((await js('window.aurora.sessionContext({mode:"normal",projectId:null})')).ok,false);assert.ok(await js('document.getElementById("mode-normal").disabled'));resolveTask();await until(async()=>!(await load()).busy);
 await js('document.getElementById("session-search").value="cactus";document.getElementById("session-search").dispatchEvent(new Event("input"))');await until(()=>js('document.querySelectorAll(".chat-link").length===2'));
 assert.ok(await js('document.getElementById("chats").textContent.includes("Earlier conversation")'));await js('Array.from(document.querySelectorAll(".chat-link")).find(b=>b.textContent.includes("Earlier conversation")).click()');await until(async()=>(await load()).currentId==='legacy');assert.equal((await load()).mode,'normal');assert.equal((await load()).activeProjectId,null);assert.equal((await load()).workspace,'');
 await fs.writeFile(path.join(output,'normal.png'),(await win.webContents.capturePage()).toPNG());
 await js(`document.getElementById('session-project').value=${JSON.stringify(project)};document.getElementById('session-project').dispatchEvent(new Event('change'))`);await until(async()=>(await load()).activeProjectId===project);assert.equal((await load()).workspace,folder);
 await js('document.getElementById("session-delete").click()');await until(()=>js('document.getElementById("delete-session-dialog").open'));await js('document.getElementById("delete-session-cancel").click()');assert.ok((await load()).chats.some(c=>c.id==='legacy'));
 await js('document.getElementById("session-delete").click();document.getElementById("delete-session-confirm").click()');await until(async()=>!(await load()).chats.some(c=>c.id==='legacy'));assert.ok(await fs.stat(folder));assert.ok((await load()).chats.some(c=>c.id===codeId));
 await until(()=>js('!document.getElementById("delete-session-dialog").open'));const saved=JSON.parse(await fs.readFile(path.join(profile,'aurora.json'),'utf8'));assert.equal(saved.projects[0].workspace,folder);assert.ok(!saved.chats.some(c=>c.id==='legacy'));
 win.setSize(950,680);await pause(200);const layout=await js(`(()=>{const library=document.querySelector('.sidebar-library').getBoundingClientRect(),bottom=document.querySelector('.sidebar-bottom').getBoundingClientRect(),composer=document.getElementById('composer').getBoundingClientRect();return {libraryBottom:library.bottom,bottomTop:bottom.top,composerBottom:composer.bottom,height:innerHeight};})()`);assert.ok(layout.libraryBottom<=layout.bottomTop+1);assert.ok(layout.composerBottom<=layout.height);await fs.writeFile(path.join(output,'compact.png'),(await win.webContents.capturePage()).toPNG());
 await fs.writeFile(path.join(output,'result.json'),JSON.stringify({passed:true,migration:true,projects:true,modePrompt:true,searchContents:true,moveSession:true,confirmedDelete:true,persistence:true,compactLayout:true}));console.log('Library smoke passed: '+output);app.exit(0);
 }catch(error){await fs.writeFile(path.join(output,'result.json'),JSON.stringify({passed:false,error:error.stack}));console.error(error);app.exit(1);}});
